### ISSUE TITLE
java exception in every step of plugin (doesn't matter which one)

### ISSUE THREAD

**Issue by osmanburucu-ibm** [UrbanCode/Ansible-Toolkit-UCD#4]
during execution i get java exceptions, but step works..
here the output of the step:
================================================================================
plugin: AnsibleToolkit, id: com.urbancode.air.plugin.AnsibleToolkit, version: 53
plugin command: '/opt/ucd/agent/opt/groovy-2.4.15/bin/groovy' '-cp' '/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/classes:/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/lib/groovy-plugin-utils-1.2.jar' '/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/file.groovy' '/opt/ucd/agent/var/temp/logs-11712852-f88a-4f52-b50f-57e741df2a0f/input.props' '/opt/ucd/agent/var/temp/logs-11712852-f88a-4f52-b50f-57e741df2a0f/output.props'
working directory: /opt/ucd/agent/var/work/apache-tomcat
properties:
  PLUGIN_INPUT_PROPS=/opt/ucd/agent/var/temp/logs-11712852-f88a-4f52-b50f-57e741df2a0f/input.props
  PLUGIN_OUTPUT_PROPS=/opt/ucd/agent/var/temp/logs-11712852-f88a-4f52-b50f-57e741df2a0f/output.props
  dest=
  group=
  mode=
  owner=
  path=/opt/webservers/sit-apache-tomcat-7.0.42
  recurse=yes
  src=
  state=directory
  with_items=
environment:
  AGENT_HOME=/opt/ucd/agent
  AH_AUTH_TOKEN=****
  AH_WEB_URL=https://cos8l.local.net:8443
  AUTH_TOKEN=****
  DS_AUTH_TOKEN=****
  DS_SYSTEM_ENCODING=UTF-8
  JAVA_OPTS=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
  PLUGIN_HOME=/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1
  UD_DIALOGUE_ID=11712852-f88a-4f52-b50f-57e741df2a0f
  WE_ACTIVITY_ID=173540b2-ed59-37d0-d2a2-9ebc4dfe4b4f
================================================================================
command is ansible-playbook tmp1594842898467.yml -vvvv
Exception in thread "Thread-1" groovy.lang.GroovyRuntimeException: exception while reading process stream
	at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:496)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:489)
	... 1 more
ansible-playbook 2.9.10
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: tmp1594842898467.yml *************************************************
Positional arguments: tmp1594842898467.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in tmp1594842898467.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
task path: /opt/ucd/agent/var/work/apache-tomcat/tmp1594842898467.yml:1
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424 && echo ansible-tmp-1594842900.3265662-53680-200575824555424="` echo /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-53672mkaps7wb/tmp0b3_yv5g TO /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424/ /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594842900.3265662-53680-200575824555424/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [file] ********************************************************************
task path: /opt/ucd/agent/var/work/apache-tomcat/tmp1594842898467.yml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955 && echo ansible-tmp-1594842901.3811712-53802-170310842457955="` echo /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/files/file.py
<localhost> PUT /root/.ansible/tmp/ansible-local-53672mkaps7wb/tmpxi4b8ml8 TO /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955/AnsiballZ_file.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955/ /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955/AnsiballZ_file.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955/AnsiballZ_file.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594842901.3811712-53802-170310842457955/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "diff": {
        "after": {
            "path": "/opt/webservers/sit-apache-tomcat-7.0.42",
            "state": "directory"
        },
        "before": {
            "path": "/opt/webservers/sit-apache-tomcat-7.0.42",
            "state": "absent"
        }
    },
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": true,
            "force": false,
            "group": null,
            "mode": null,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": null,
            "path": "/opt/webservers/sit-apache-tomcat-7.0.42",
            "recurse": true,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": null
        }
    },
    "mode": "0775",
    "owner": "root",
    "path": "/opt/webservers/sit-apache-tomcat-7.0.42",
    "size": 6,
    "state": "directory",
    "uid": 0
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by osmanburucu-ibm** [comment]
another step output:
================================================================================
plugin: AnsibleToolkit, id: com.urbancode.air.plugin.AnsibleToolkit, version: 53
plugin command: '/opt/ucd/agent/opt/groovy-2.4.15/bin/groovy' '-cp' '/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/classes:/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/lib/groovy-plugin-utils-1.2.jar' '/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1/ashell.groovy' '/opt/ucd/agent/var/temp/logs-f193b582-41c9-478e-8bba-2f7fda85daa6/input.props' '/opt/ucd/agent/var/temp/logs-f193b582-41c9-478e-8bba-2f7fda85daa6/output.props'
working directory: /opt/ucd/agent/var/work/apache-tomcat
properties:
  PLUGIN_INPUT_PROPS=/opt/ucd/agent/var/temp/logs-f193b582-41c9-478e-8bba-2f7fda85daa6/input.props
  PLUGIN_OUTPUT_PROPS=/opt/ucd/agent/var/temp/logs-f193b582-41c9-478e-8bba-2f7fda85daa6/output.props
  script=  - name: change non ssl ports in server.xml
    replace:
      path: /opt/webservers/sit-apache-tomcat-7.0.42/conf/server.xml
      regexp: "8080" 
      replace: 8085
environment:
  AGENT_HOME=/opt/ucd/agent
  AH_AUTH_TOKEN=****
  AH_WEB_URL=https://cos8l.local.net:8443
  AUTH_TOKEN=****
  DS_AUTH_TOKEN=****
  DS_SYSTEM_ENCODING=UTF-8
  JAVA_OPTS=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
  PLUGIN_HOME=/opt/ucd/agent/var/plugins/com.urbancode.air.plugin.AnsibleToolkit_53_64fea7060cb6109785ac23130dd0820245a7b0a452098e29b4fbbbfe57ca65c1
  UD_DIALOGUE_ID=f193b582-41c9-478e-8bba-2f7fda85daa6
  WE_ACTIVITY_ID=173540b2-ed66-1b18-48e9-a454b05cb384
================================================================================
command is ansible-playbook tmp1594842909259.yml -vvvv
Exception in thread "Thread-1" groovy.lang.GroovyRuntimeException: exception while reading process stream
	at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:496)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.codehaus.groovy.runtime.ProcessGroovyMethods$TextDumper.run(ProcessGroovyMethods.java:489)
	... 1 more
ansible-playbook 2.9.10
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: tmp1594842909259.yml *************************************************
Positional arguments: tmp1594842909259.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in tmp1594842909259.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
task path: /opt/ucd/agent/var/work/apache-tomcat/tmp1594842909259.yml:1
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713 && echo ansible-tmp-1594842911.0059683-54084-37168669251713="` echo /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-54076djucnnd8/tmpy_5lwfjk TO /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713/ /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594842911.0059683-54084-37168669251713/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [change non ssl ports in server.xml] **************************************
task path: /opt/ucd/agent/var/work/apache-tomcat/tmp1594842909259.yml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523 && echo ansible-tmp-1594842912.2821474-54208-3673205788523="` echo /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/files/replace.py
<localhost> PUT /root/.ansible/tmp/ansible-local-54076djucnnd8/tmpzaextpb4 TO /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523/AnsiballZ_replace.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523/ /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523/AnsiballZ_replace.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523/AnsiballZ_replace.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594842912.2821474-54208-3673205788523/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "attributes": null,
            "backup": false,
            "before": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "encoding": "utf-8",
            "follow": false,
            "force": null,
            "group": null,
            "mode": null,
            "owner": null,
            "path": "/opt/webservers/sit-apache-tomcat-7.0.42/conf/server.xml",
            "regexp": "8080",
            "remote_src": null,
            "replace": "8085",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "3 replacements made"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
